#!/usr/bin/env php
<?php

$dir = __DIR__ . '/inbox';

if (!is_dir($dir)) {
    @mkdir($dir, 0777, true);
}
if (!is_dir($dir)) {
    exit;
}

$mail = '';
while (false !== ($line = fgets(STDIN))) {
    $mail .= $line;
}

$path = $dir . '/' . generate_message_filename();

file_put_contents($path, $mail);

function generate_message_filename()
{
    $time = microtime(true);
    return date('Ymd-His-', $time) . sprintf('%04d', (int)(($time - (int)$time) * 10000)) . '-' . sprintf('%04d', mt_rand(0, 10000)) . '.eml';
}
